### ISSUE TITLE
can we port this to android ?

### ISSUE THREAD

**Issue by parthindia47** [yerofey/cryptowallet-cli#1]
hello can we port this to android ?

**Comment by yerofey** [comment]
> hello can we port this to android ?
As an app?

**Comment by parthindia47** [comment]
Yes as an app , and few more questions.
ideally an online wallet have these functions as well : send , receive and show balance.

let say I create a wallet address and send some token/coin from binance to public address. 
1. how can i see balance ?
2. how can i send back this coins to another wallet ?

Thanks

**Comment by yerofey** [comment]
> Yes as an app , and few more questions.
> ideally an online wallet have these functions as well : send , receive and show balance.
> 
> let say I create a wallet address and send some token/coin from binance to public address.
> 
> 1. how can i see balance ?
> 2. how can i send back this coins to another wallet ?
> 
> Thanks

Well, this is not a "real wallet", my tool only generates you the new crypto wallet, that you can import in any wallet app (MetaMask, Trust Wallet, hardware wallet, etc...)
