### ISSUE TITLE
Please add suffix

### ISSUE THREAD

**Issue by pavanansible** [yerofey/cryptowallet-cli#5]
Good Project, very useful and helpful, can you please consider and implement on below requirement's.

Kindly add suffix like below
exp: cw -c ETH -p 000  -s 000

For standalone machine without internet connected, if possible please provide binaries (linux) without download/compile it.

**Comment by yerofey** [comment]
Hey, thanks for the feedback! 
What do you mean by suffix - it can be anywhere in address or like at the end?

**Comment by pavanansible** [comment]
at the end,  like below
exp: cw -c ETH -p 111 -s 111
      
ETH address output like:  0x111XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX111

**Comment by yerofey** [comment]
Okay, I'll do that soon.

**Comment by yerofey** [comment]
I've added `suffix` support, but not fully tested it. Currently it's on dev release. You can install on your machine and try it out.

```bash
# via Yarn
$ yarn global add @yerofey/cryptowallet-cli@dev

# or via NPM
$ npm i -g @yerofey/cryptowallet-cli@dev
```

**Comment by pavanansible** [comment]
Works very well, you made my day, I am searching in Internet very longtime for generate mnemonic with customer address.
Thank you very much, Please close this issue

**Comment by yerofey** [comment]
I have to test it properly, then I'll push this version to the master branch.
