### ISSUE TITLE
using n wallets -> CSV ?

### ISSUE THREAD

**Issue by d4op** [yerofey/cryptowallet-cli#7]
is there an option for creating multiple wallets like the n option with output CSV ?
like:
public;priv;memoric;type

**Comment by yerofey** [comment]
I can do that

**Comment by yerofey** [comment]
Check out the latest version (v1.6.0), kinda did what you wanted, improvements will be added soon as well.

**Comment by yerofey** [comment]
Example:
`cw -c btc -o csv -F out.csv -n 10`

**Comment by yerofey** [comment]
Note that some data like mnemonic and extended private key will be displayed in the console. Maybe I'll fix that in next update, currently it's like that.
