### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by d4op** [yerofey/cryptowallet-cli#8]
sudo npm i -g @yerofey/cryptowallet-cli
(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠼ idealTree:tronweb: sill fetch manifest @types/duplexify@*
(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠧ idealTree:tronweb: sill fetch manifest @types/duplexify@*
(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠧ idealTree:tronweb: sill fetch manifest @types/duplexify@*
(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠋ idealTree:tronweb: sill fetch manifest @types/duplexify@*
npm ERR! code 128
npm ERR! An unknown git error occurred
**npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/web3-js/scrypt-shim.git
npm ERR! Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.**
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

**Comment by yerofey** [comment]
Can you provide more info about your setup: OS, etc.
